language: generic

sudo: required
services:
  - docker

env:
  global:
    - SHA=$(git rev-parse HEAD)
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1

before_install:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t sssuthe/todo-list-client:latest -t sssuthe/todo-list-client:$SHA .
  - docker push sssuthe/todo-list-client:latest
  - docker push sssuthe/todo-list-client:$SHA

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "shark-ops"
  env: "SharkOpsClient-env"
  bucket_name: "elasticbeanstalk-us-east-1-033966497385"
  bucket_path: "shark-ops-client"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
